// Generated by Wrangler by running `wrangler types`

interface Env {
	DOTENV_PUBLIC_KEY: string;
	SHOPIFY_SHOP_DOMAIN: string;
	SHOPIFY_WEBHOOK_SECRET: string;
	ZALO_APP_ID: string;
	ZALO_APP_SECRET: string;
	ZALO_OA_ID: string;
	ZALO_ACCESS_TOKEN: string;
	ZALO_REFRESH_TOKEN: string;
	ZALO_TEMPLATE_ID: string;
	ADMIN_PASSWORD: string;
	DB: D1Database;
}
